### PR TITLE
Toast

### PR DESCRIPTION
**Pull request by Logan1x**

### CODE REVIEW

**Review by surajmore98 — APPROVED** [review]

**Comment by surajmore98** [comment]
@Logan1x https://deploy-preview-4--libreui.netlify.app/drawer/drawer.html should look like this only?

**Review by Hnh013 — APPROVED** [review]
looks good to merge!

**Comment by Logan1x** [comment]
@surajmore98 it will look like this : https://deploy-preview-4--libreui.netlify.app/toast/toast.html

**Comment by Logan1x** [comment]
Thanks, @Hnh013 and @surajmore98 , merging now :)

**Pull request merged**
