### PR TITLE
"Feat: added input component"

### PR DESCRIPTION
**Pull request by Logan1x**
Reverts Logan1x/LibreUI#10

### CODE REVIEW

**Review by thegeorgenikhil — APPROVED** [review]
Good to merge!

**Review by vinc3nati — APPROVED** [review]
changes looks good!

**Review by varnita619 — APPROVED** [review]
Looks good

**Comment by Logan1x** [comment]
Thanks vinc3nati, thegeorgenikhil, and varnita619 for PR reviews :)

**Pull request merged**
