### PR TITLE
Image

### PR DESCRIPTION
**Pull request by Logan1x**

### CODE REVIEW

**Comment by Logan1x** [comment]
Preview link : https://deploy-preview-13--libreui.netlify.app/image/image.html

**Review by anuj-kumary — COMMENTED** [review]
You have to add one image for a hero section like for big width and height and make that image responsive.

**Comment by SJTGSHIVAM** [comment]
Its a small piece of change looks quite clean and ready to merge!

**Comment by Logan1x** [comment]
Thanks @SJTGSHIVAM & @anuj-kumary for review :)

**Pull request merged**
